# Generated by Django 5.1.2 on 2024-11-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False, verbose_name='id_mascota')),
                ('nombre', models.CharField(max_length=64, verbose_name='Nombre Mascota')),
                ('edad', models.IntegerField(max_length=2, null=True, verbose_name='Edad Mascota')),
                ('especie', models.CharField(max_length=32, verbose_name='Especie Mascota')),
                ('raza', models.CharField(max_length=32, null=True, verbose_name='Raza Mascota')),
                ('descripcion', models.TextField(max_length=254, verbose_name='Descripcion Mascota')),
                ('ubicacion', models.CharField(max_length=64, verbose_name='Ubicacion Mascota')),
                ('estado', models.CharField(max_length=20, null=True, verbose_name='Estado Mascota')),
                ('fecha_registro', models.DateField(verbose_name='Fecha de Registro')),
            ],
        ),
    ]
