# Generated by Django 5.1.2 on 2024-11-04 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False, verbose_name='id_mascota')),
                ('nombre', models.CharField(max_length=64, verbose_name='Nombre Mascota')),
                ('edad', models.IntegerField(null=True, verbose_name='Edad Mascota')),
                ('especie', models.CharField(max_length=32, verbose_name='Especie Mascota')),
                ('raza', models.CharField(max_length=32, null=True, verbose_name='Raza Mascota')),
                ('descripcion', models.TextField(max_length=254, verbose_name='Descripcion Mascota')),
                ('ubicacion', models.CharField(max_length=64, verbose_name='Ubicacion Mascota')),
                ('estado', models.CharField(max_length=20, null=True, verbose_name='Estado Mascota')),
                ('fecha_registro', models.DateField(verbose_name='Fecha de Registro')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de mensaje')),
                ('id_remitente', models.CharField(blank=True, max_length=20, null=True)),
                ('id_destinatario', models.CharField(blank=True, max_length=20, null=True)),
                ('id_publicacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_envio', models.DateField(verbose_name='Fecha de envio')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id_publicacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Publicacion')),
                ('id_usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('id_mascota', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_publicacion', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=20, null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Usuario')),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('apellido', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('contraseña', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('edad', models.CharField(blank=True, max_length=10, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=20, null=True)),
                ('fono', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Mascotas',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.publicacion'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
    ]
