# Generated by Django 5.1 on 2024-11-04 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mascota_mensaje_publicacion_usuario_delete_mascotas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='contrasenia',
        ),
    ]
