# Generated by Django 5.1.3 on 2024-11-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_contraseña_usuario_contrasenia'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rut',
            field=models.CharField(default='none', max_length=12),
        ),
    ]
