# Generated by Django 5.1.3 on 2024-11-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuario_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contrasenia',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contraseña'),
        ),
    ]
