# Generated by Django 5.1.3 on 2024-11-19 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_usuario_contrasenia'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='id_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
            preserve_default=False,
        ),
    ]
