# Generated by Django 5.1.3 on 2024-11-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mascota_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(blank=True, default='null', null=True, upload_to=''),
        ),
    ]
