# Generated by Django 5.1.1 on 2024-12-09 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_mascota_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='id_destinatario',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='publicacion',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='mascota',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='contenido',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='id_mensaje',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id mensaje'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='id_publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.publicacion'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='id_remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='id_mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mascota'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mascota', models.ManyToManyField(to='core.mascota')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
    ]
