# Generated by Django 5.1.1 on 2024-12-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_mensaje_id_destinatario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Comuna')),
                ('nombre', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(blank=True, default='null', null=True, upload_to='mascotas/'),
        ),
    ]
