# Generated by Django 5.1.1 on 2024-12-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_comuna_alter_mascota_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna',
            name='nombre',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
