# Generated by Django 5.1.1 on 2024-12-10 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_usuario_comuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='comuna',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.CASCADE, to='core.comuna'),
        ),
    ]
